spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.f51c6d73dbd4228c
            clientSecret: 3d6af5ef2974a7a8c38c12bb5e1aaa19fd5ed84b
          
          
                
         
